from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query, Response
from sqlalchemy.orm import Session
from sqlalchemy import func
from app.database import get_db
from app.models.user import User, UserRole
from app.schemas.user import UserCreate, UserUpdate, UserResponse, ChangePassword
from app.api.deps import get_current_user, require_role
from app.core.security import get_password_hash

router = APIRouter()


@router.get("/stats")
async def get_user_stats(
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role([UserRole.ADMIN, UserRole.OWNER]))
):
    """
    Get global user count by role (active users only).
    """
    results = db.query(User.role, func.count(User.id)).filter(
        User.is_active == True
    ).group_by(User.role).all()

    stats = {"vendedor": 0, "logistica": 0, "admin": 0, "owner": 0}
    for role, count in results:
        role_key = role.value if hasattr(role, 'value') else str(role)
        if role_key in stats:
            stats[role_key] = count

    return stats


@router.get("/", response_model=List[UserResponse])
async def get_users(
    response: Response,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    role_filter: Optional[str] = None,
    search: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get list of users with optional filtering.
    """
    # Only admin and owner can view all users
    if current_user.role not in ["admin", "owner"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
    
    from sqlalchemy.orm import joinedload
    query = db.query(User).options(joinedload(User.substitute))
    
    # Filter by role
    if role_filter:
        query = query.filter(User.role == role_filter)
    
    # Search in multiple fields
    if search:
        search_filter = f"%{search}%"
        query = query.filter(
            (User.name.ilike(search_filter)) |
            (User.email.ilike(search_filter)) |
            (User.legajo.ilike(search_filter))
        )
    
    # Only show active users
    query = query.filter(User.is_active == True)
    
    # Calculate total count before pagination
    total_count = query.count()
    response.headers["X-Total-Count"] = str(total_count)

    users = query.offset(skip).limit(limit).all()
    return users


@router.get("/{user_id}", response_model=UserResponse)
async def get_user(
    user_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get a specific user by ID.
    """
    # Only admin/owner can view other users, or user can view themselves
    if current_user.role not in ["admin", "owner"] and current_user.id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
    
    from sqlalchemy.orm import joinedload
    user = db.query(User).options(joinedload(User.substitute)).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
    return user


@router.post("/", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
async def create_user(
    user: UserCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Create a new user. Legajo is auto-generated by the backend.
    
    Args:
        user: User data
        db: Database session
        current_user: Current authenticated user
        
    Returns:
        Created user
        
    Raises:
        HTTPException: If email already exists, or no permissions
    """
    # Only admin and owner can create users
    if current_user.role not in ["admin", "owner"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
    
    # Check if email already exists
    existing_user = db.query(User).filter(User.email == user.email).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User with this email already exists"
        )
    
    # Auto-generate legajo: query ALL users (including inactive) to avoid collisions
    import re
    all_legajos = db.query(User.legajo).all()
    max_num = 0
    for (legajo,) in all_legajos:
        if legajo:
            match = re.match(r"LEG-(\d+)", legajo)
            if match:
                num = int(match.group(1))
                if num > max_num:
                    max_num = num
    generated_legajo = f"LEG-{str(max_num + 1).zfill(3)}"
    
    # Create new user with hashed password
    user_data = user.model_dump(exclude={"password", "legajo"})
    user_data["password_hash"] = get_password_hash(user.password)
    user_data["legajo"] = generated_legajo
    
    db_user = User(**user_data)
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    
    return db_user


@router.put("/{user_id}", response_model=UserResponse)
async def update_user(
    user_id: int,
    user: UserUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Update a user.
    
    Args:
        user_id: User ID
        user: Updated user data
        db: Database session
        current_user: Current authenticated user
        
    Returns:
        Updated user
        
    Raises:
        HTTPException: If user not found or no permissions
    """
    # Only admin/owner can update other users, or user can update themselves
    if current_user.role not in ["admin", "owner"] and current_user.id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
    
    db_user = db.query(User).filter(User.id == user_id).first()
    if not db_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
    
    # Prevent users from changing their own role (only admin/owner can)
    if current_user.id == user_id and user.role and current_user.role not in ["admin", "owner"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Cannot change your own role"
        )
    
    # Update user fields
    update_data = user.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        setattr(db_user, field, value)
    
    db.commit()
    db.refresh(db_user)
    
    return db_user


@router.delete("/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_user(
    user_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Delete a user (soft delete).
    
    Args:
        user_id: User ID
        db: Database session
        current_user: Current authenticated user
        
    Raises:
        HTTPException: If user not found, no permissions, or trying to delete self
    """
    # Only admin and owner can delete users
    if current_user.role not in ["admin", "owner"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
    
    # Prevent users from deleting themselves
    if current_user.id == user_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Cannot delete your own account"
        )
    
    db_user = db.query(User).filter(User.id == user_id).first()
    if not db_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
    
    # Soft delete: mark as inactive
    db_user.is_active = False
    db.commit()
    
    return None


@router.put("/{user_id}/password", status_code=status.HTTP_204_NO_CONTENT)
async def change_user_password(
    user_id: int,
    body: ChangePassword,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Change a user's password.
    
    Args:
        user_id: User ID
        new_password: New password
        db: Database session
        current_user: Current authenticated user
        
    Raises:
        HTTPException: If user not found or no permissions
    """
    # Only admin/owner can change other users' passwords, or user can change their own
    if current_user.role not in ["admin", "owner"] and current_user.id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
    
    db_user = db.query(User).filter(User.id == user_id).first()
    if not db_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
    
    # Update password
    db_user.password_hash = get_password_hash(body.new_password)
    db.commit()
    
    return None


@router.patch("/{user_id}/leave", response_model=UserResponse)
async def set_user_leave(
    user_id: int,
    substitute_id: int = Query(..., description="ID of the substitute user"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Mark a user as on leave and assign a substitute.
    
    Args:
        user_id: ID of the user going on leave
        substitute_id: ID of the substitute user
        db: Database session
        current_user: Current authenticated user
        
    Returns:
        Updated user
        
    Raises:
        HTTPException: If user/substitute not found, roles don't match, or no permissions
    """
    # Only admin/owner can set leave for others (or maybe the user themselves?)
    # Instructions say: "El rol Owner puede marcar a un empleado..."
    if current_user.role not in ["admin", "owner"] and current_user.id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
    
    # Get user going on leave
    db_user = db.query(User).filter(User.id == user_id).first()
    if not db_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
        
    # Get substitute user
    substitute = db.query(User).filter(User.id == substitute_id).first()
    if not substitute:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Substitute user not found"
        )
        
    # Check if substitute is active
    if not substitute.is_active:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Substitute user is not active"
        )

    # Check if substitute is already on leave (cannot substitute if on leave)
    if substitute.is_on_leave:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"El suplente {substitute.name} está de vacaciones. No puede ser asignado."
        )

    # STRICT RULE: Substitute must have the exact same role
    if db_user.role != substitute.role:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Substitute must have the same role. User: {db_user.role}, Substitute: {substitute.role}"
        )
        
    # Prevent self-substitution (makes no sense)
    if db_user.id == substitute.id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Cannot substitute yourself"
        )

    # Check if user is currently a substitute for someone else who is on leave
    # If they are covering for someone, they cannot go on leave themselves until that coverage ends
    active_substitutions = db.query(User).filter(
        User.substitute_id == user_id,
        User.is_on_leave == True
    ).first()
    
    if active_substitutions:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"No puede tomar vacaciones mientras sea suplente de {active_substitutions.name}. Debe finalizar esa suplencia primero."
        )
    
    # Apply changes
    db_user.is_on_leave = True
    db_user.substitute_id = substitute.id
    db.commit()
    db.refresh(db_user)
    
    return db_user


@router.patch("/{user_id}/return", response_model=UserResponse)
async def return_from_leave(
    user_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Mark a user as returned from leave.
    
    Args:
        user_id: User ID
        
    Returns:
        Updated user
    """
    if current_user.role not in ["admin", "owner"] and current_user.id != user_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions"
        )
        
    db_user = db.query(User).filter(User.id == user_id).first()
    if not db_user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
        
    db_user.is_on_leave = False
    db_user.substitute_id = None
    db.commit()
    db.refresh(db_user)
    
    return db_user
