"""add business configs table

Revision ID: 6149834ee3d1
Revises: 7f36b449f8af
Create Date: 2026-02-06 01:09:29.973405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6149834ee3d1'
down_revision: Union[str, None] = '7f36b449f8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_threshold_1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage_1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_threshold_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage_2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_configs')
    # ### end Alembic commands ###
