"""add user_id to clients

Revision ID: 8bfca757e772
Revises: 99ab8e67d008
Create Date: 2026-02-06 02:27:53.334471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8bfca757e772'
down_revision: Union[str, None] = '99ab8e67d008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
