"""remove call logs

Revision ID: a415e21f12d2
Revises: c7de11a5dcde
Create Date: 2026-02-10 21:36:23.935334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a415e21f12d2'
down_revision: Union[str, None] = 'c7de11a5dcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_logs')
    op.create_index(op.f('ix_business_configs_id'), 'business_configs', ['id'], unique=False)
    op.create_index(op.f('ix_client_printers_id'), 'client_printers', ['id'], unique=False)
    op.drop_index('ix_clients_tipo_cliente', table_name='clients')
    op.create_index(op.f('ix_clients_priority'), 'clients', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_priority'), table_name='clients')
    op.create_index('ix_clients_tipo_cliente', 'clients', ['priority'], unique=False)
    op.drop_index(op.f('ix_client_printers_id'), table_name='client_printers')
    op.drop_index(op.f('ix_business_configs_id'), table_name='business_configs')
    op.create_table('call_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('call_date', sa.DATE(), nullable=False),
    sa.Column('industry', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('uses_printers', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('printer_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('interested_in_quote', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='call_logs_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='call_logs_ibfk_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_call_logs_seller_id', 'call_logs', ['seller_id'], unique=False)
    op.create_index('ix_call_logs_id', 'call_logs', ['id'], unique=False)
    op.create_index('ix_call_logs_client_id', 'call_logs', ['client_id'], unique=False)
    op.create_index('ix_call_logs_call_date', 'call_logs', ['call_date'], unique=False)
    # ### end Alembic commands ###
