"""add_role_permissions_to_config

Revision ID: d3c03fbeee2b
Revises: 8bfca757e772
Create Date: 2026-02-06 03:24:38.038962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3c03fbeee2b'
down_revision: Union[str, None] = '8bfca757e772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_configs', sa.Column('role_permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_configs', 'role_permissions')
    # ### end Alembic commands ###
